name: CI
on:
  - pull_request
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install qemu-utils
        run: |
          sudo apt-get update
          sudo apt-get install qemu-utils

      - uses: actions/checkout@v2

      - name: Build image
        run: |
          sudo ./alpine-make-vm-image \
              --image-format qcow2 \
              --image-size 4G \
              --repositories-file veza/repositories \
              --packages "$(cat veza/packages)" \
              --fs-skel-dir veza/rootfs \
              --fs-skel-chown root:root \
              --script-chroot \
              veza_insight_point.qcow2 -- ./veza/configure.sh

      - name: Convert image to OVA
        run: |
          mkdir ova_out
          qemu-img convert -p -f qcow2 -O vmdk veza_insight_point.qcow2 ova_out/veza_insight_point.vmdk
          sed "s/<Version><\/Version>/<Version>$(date +%Y%m%d)<\/Version>/g" veza/veza_insight_point.ovf > ova_out/veza_insight_point.ovf
          echo $(openssl sha1 ova_out/veza_insight_point.ovf) > ova_out/veza_insight_point.mf
          echo $(openssl sha1 ova_out/veza_insight_point.vmdk) >> ova_out/veza_insight_point.mf
          tar cf ova_out/veza_insight_point.ova ova_out/veza_insight_point.vmdk ova_out/veza_insight_point.mf ova_out/veza_insight_point.ovf

      - name: Upload OVA
        uses: actions/upload-artifact@v3
        with:
          name: 'OVA'
          path: '*.ova'
